language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose
  - cargo clean
  - cargo test --verbose --features chess
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true