[package]
name = "vampirc-uci"
version = "0.4.0"
description = "A Universal Chess Interface (UCI) protocol parser and serializer."
documentation = "https://docs.rs/vampirc_uci"
license = "MIT"
readme = "README.md"
keywords = ["uci", "chess", "parser"]
authors = ["Matija Kejžar <matija@kejzar.si>"]
edition = "2018"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
